### ISSUE TITLE
[Enhancement] simplify by using callable events

### ISSUE THREAD

**Issue by israel-dryer** [israel-dryer/Text-Code-Editor#8]
Try to simplify if possible by using callable events. Some of the functions may need parameters... So will need to see if this is feasible on this particular project. Also may be able to leverage meta data for this... passing it as parameters and using the key/event combo like a decorator 🤔

```python
import PySimpleGUI as sg

def func():
    print('func was called')
	
window = sg.Window('app', layout=[[sg.Button('Push', key=func)]], finalize=True)

while True:
    event, values = window.read()
    if event in (None, 'Exit'):
    	break
    if callable(event):
        event()
    else:
        print(event, values)
```

**Comment by PySimpleGUI** [comment]
Don't do it

From the Zen of Python:
> Explicit is better than implicit.
> Simple is better than complex.

You had a nice, beautifully easy to understand event loop that is going to be destroyed in order to make it "appear" less complex.  Sure, you've reduced the number of lines in that part of the code, bu you're about it make the overall project much more complex by including functions inside your Element definitions.

Sometimes it's better to put down the pen and stop, calling it "done".  Overworking it is not going to make it better in this case.  It's going to make it much worse.

**Comment by PySimpleGUI** [comment]
This "trick" is one I'm regretting telling anyone.  I've not released any code that does this because I realized it was a bad ideas.  It brings back the "Callback" way of event handling, something that PySimpleGUI, with great effort, **removed** from the GUI experience.  This trick is essentially re-creating all the things that I considered "bad" about tkinter, Qt that I wanted to get rid of.

**Comment by israel-dryer** [comment]
Haha. I literally just had a "yeah that was a bad idea" moment right before I saw your message.

**Comment by PySimpleGUI** [comment]
Close this one?  It makes me nervous to see :-)

**Comment by israel-dryer** [comment]
haha. done.
